#!/usr/bin/env python3
from __future__ import annotations

import base64
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

PATCH_ID = "MEMEFLOW_DISCOVERY_NATIVE_PLATFORM_V3"
OLD_V2 = "MEMEFLOW_DISCOVERY_PLATFORM_DROPDOWN_V2"
STAMP = time.strftime("%Y%m%d-%H%M%S")
RUNTIME = base64.b64decode("CigoKSA9PiB7CiAgJ3VzZSBzdHJpY3QnOwoKICBjb25zdCBQQVRDSCA9ICdNRU1FRkxPV19ESVNDT1ZFUllfTkFUSVZFX1BMQVRGT1JNX1YzJzsKICBpZiAod2luZG93Ll9fbWZEaXNjb3ZlcnlOYXRpdmVQbGF0Zm9ybVYzKSByZXR1cm47CiAgd2luZG93Ll9fbWZEaXNjb3ZlcnlOYXRpdmVQbGF0Zm9ybVYzID0gdHJ1ZTsKCiAgY29uc3Qgc3RhdGUgPSB7CiAgICBtb2RlOiBudWxsLAogICAgYnVzeTogZmFsc2UsCiAgICBjYXJkOiBudWxsLAogICAgdmFsdWVFbDogbnVsbCwKICAgIHNlbGVjdDogbnVsbCwKICAgIG9ic2VydmVyOiBudWxsLAogICAgcG9sbDogbnVsbCwKICAgIHJlZnJlc2hUaW1lcjogbnVsbCwKICAgIGNvbXBhdFRpbWVyOiBudWxsCiAgfTsKCiAgY29uc3QgUFVNUF9PTkxZID0gWwogICAgewogICAgICBpZDogJ2JvbmRpbmcnLAogICAgICB0ZXN0OiB0ID0+IC9cYmJvbmRpbmdccypjdXJ2ZVxiL2kudGVzdCh0KSwKICAgICAgZGV4OiAnUHVtcC5mdW4gb25seSDCtyBpbmFjdGl2ZSBpbiBERVggbW9kZScsCiAgICAgIGh5YnJpZDogJ1B1bXAuZnVuIG9ubHkgwrcgaWdub3JlZCBieSB0aGUgREVYIGJyYW5jaCcKICAgIH0sCiAgICB7CiAgICAgIGlkOiAnZmVlcycsCiAgICAgIHRlc3Q6IHQgPT4gL1xidG90YWxccytmZWVzP1xiL2kudGVzdCh0KSwKICAgICAgZGV4OiAnUHVtcC5mdW4gb25seSDCtyBpbmFjdGl2ZSBpbiBERVggbW9kZScsCiAgICAgIGh5YnJpZDogJ1B1bXAuZnVuIG9ubHkgwrcgaWdub3JlZCBieSB0aGUgREVYIGJyYW5jaCcKICAgIH0sCiAgICB7CiAgICAgIGlkOiAnZGV2ZWxvcGVyJywKICAgICAgdGVzdDogdCA9PiAvXGJkZXZlbG9wZXJcYi9pLnRlc3QodCkgJiYgKAogICAgICAgIC9cYnNoYXJlXGIvaS50ZXN0KHQpIHx8CiAgICAgICAgL1xiY29uY2VudHJhdGlvblxiL2kudGVzdCh0KSB8fAogICAgICAgIC9cYndhbGxldFxiL2kudGVzdCh0KSB8fAogICAgICAgIC9cYmJsYWNrbGlzdFxiL2kudGVzdCh0KSB8fAogICAgICAgIC9cYm1pbig/OmltdW0pP1xiL2kudGVzdCh0KSB8fAogICAgICAgIC9cYm1heCg/OmltdW0pP1xiL2kudGVzdCh0KSB8fAogICAgICAgIC8lLy50ZXN0KHQpCiAgICAgICksCiAgICAgIGRleDogJ0NyZWF0b3IvZGV2ZWxvcGVyIHNpZ25hbCBpcyB1bmF2YWlsYWJsZSBmcm9tIHRoZSBERVggcG9vbCDCtyBpbmFjdGl2ZScsCiAgICAgIGh5YnJpZDogJ0FwcGxpZWQgdG8gUHVtcC5mdW4gdG9rZW5zIG9ubHkgwrcgaWdub3JlZCBieSB0aGUgREVYIGJyYW5jaCcKICAgIH0sCiAgICB7CiAgICAgIGlkOiAnYnVuZGxlJywKICAgICAgdGVzdDogdCA9PiAvXGJidW5kbGVcYi9pLnRlc3QodCksCiAgICAgIGRleDogJ05vIERFWCBidW5kbGUgc2lnbmFsIGluIHRoaXMgYnVpbGQgwrcgaW5hY3RpdmUnLAogICAgICBoeWJyaWQ6ICdQdW1wLmZ1biBicmFuY2ggb25seSDCtyBubyBERVggYnVuZGxlIHNpZ25hbCcKICAgIH0sCiAgICB7CiAgICAgIGlkOiAnc25pcGVyJywKICAgICAgdGVzdDogdCA9PiAvXGJzbmlwZXJcYi9pLnRlc3QodCksCiAgICAgIGRleDogJ05vIERFWCBzbmlwZXIgc2lnbmFsIGluIHRoaXMgYnVpbGQgwrcgaW5hY3RpdmUnLAogICAgICBoeWJyaWQ6ICdQdW1wLmZ1biBicmFuY2ggb25seSDCtyBubyBERVggc25pcGVyIHNpZ25hbCcKICAgIH0KICBdOwoKICBjb25zdCBjc3MgPSBgCiAgICAvKiBLaWxsIGFsbCBzdXBlcnNlZGVkIGN1c3RvbSBkaXNjb3ZlcnkgbWVudXMvcGFuZWxzLiAqLwogICAgI21mZHMtcGFuZWwtdjEsCiAgICAjbWZkeC1wbGF0Zm9ybS1tZW51LXYyIHsKICAgICAgZGlzcGxheTogbm9uZSAhaW1wb3J0YW50OwogICAgICBwb2ludGVyLWV2ZW50czogbm9uZSAhaW1wb3J0YW50OwogICAgfQoKICAgIC5tZmRuLXBsYXRmb3JtLWNhcmQtdjMgewogICAgICBwb3NpdGlvbjogcmVsYXRpdmUgIWltcG9ydGFudDsKICAgICAgY3Vyc29yOiBwb2ludGVyICFpbXBvcnRhbnQ7CiAgICAgIC13ZWJraXQtdGFwLWhpZ2hsaWdodC1jb2xvcjogdHJhbnNwYXJlbnQ7CiAgICAgIHRvdWNoLWFjdGlvbjogbWFuaXB1bGF0aW9uOwogICAgfQoKICAgIC5tZmRuLXBsYXRmb3JtLWNhcmQtdjM6OmFmdGVyIHsKICAgICAgY29udGVudDogIiI7CiAgICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTsKICAgICAgcmlnaHQ6IDE0cHg7CiAgICAgIHRvcDogNTAlOwogICAgICB3aWR0aDogN3B4OwogICAgICBoZWlnaHQ6IDdweDsKICAgICAgbWFyZ2luLXRvcDogLTVweDsKICAgICAgYm9yZGVyLXJpZ2h0OiAxLjRweCBzb2xpZCAjNmU4OTk1OwogICAgICBib3JkZXItYm90dG9tOiAxLjRweCBzb2xpZCAjNmU4OTk1OwogICAgICB0cmFuc2Zvcm06IHJvdGF0ZSg0NWRlZyk7CiAgICAgIHBvaW50ZXItZXZlbnRzOiBub25lOwogICAgICB6LWluZGV4OiAzOwogICAgfQoKICAgICNtZmRuLW5hdGl2ZS1wbGF0Zm9ybS12MyB7CiAgICAgIHBvc2l0aW9uOiBhYnNvbHV0ZSAhaW1wb3J0YW50OwogICAgICBpbnNldDogMCAhaW1wb3J0YW50OwogICAgICB6LWluZGV4OiA0ICFpbXBvcnRhbnQ7CiAgICAgIHdpZHRoOiAxMDAlICFpbXBvcnRhbnQ7CiAgICAgIGhlaWdodDogMTAwJSAhaW1wb3J0YW50OwogICAgICBtaW4td2lkdGg6IDAgIWltcG9ydGFudDsKICAgICAgbWFyZ2luOiAwICFpbXBvcnRhbnQ7CiAgICAgIHBhZGRpbmc6IDAgIWltcG9ydGFudDsKICAgICAgYm9yZGVyOiAwICFpbXBvcnRhbnQ7CiAgICAgIGJvcmRlci1yYWRpdXM6IGluaGVyaXQgIWltcG9ydGFudDsKICAgICAgYmFja2dyb3VuZDogdHJhbnNwYXJlbnQgIWltcG9ydGFudDsKICAgICAgY29sb3I6IHRyYW5zcGFyZW50ICFpbXBvcnRhbnQ7CiAgICAgIG9wYWNpdHk6IDAuMDAxICFpbXBvcnRhbnQ7CiAgICAgIGZvbnQtc2l6ZTogMTZweCAhaW1wb3J0YW50OyAvKiBwcmV2ZW50cyBpT1Mgem9vbSAqLwogICAgICBhcHBlYXJhbmNlOiBhdXRvICFpbXBvcnRhbnQ7CiAgICAgIC13ZWJraXQtYXBwZWFyYW5jZTogbWVudWxpc3QgIWltcG9ydGFudDsKICAgICAgY3Vyc29yOiBwb2ludGVyICFpbXBvcnRhbnQ7CiAgICAgIC13ZWJraXQtdGFwLWhpZ2hsaWdodC1jb2xvcjogdHJhbnNwYXJlbnQ7CiAgICB9CgogICAgLm1mZG4tcGxhdGZvcm0tY2FyZC12My5tZmRuLWJ1c3ktdjMgewogICAgICBvcGFjaXR5OiAuNjIgIWltcG9ydGFudDsKICAgIH0KCiAgICAubWZkbi1jb21wYXQtY2FyZC12MyB7CiAgICAgIHBvc2l0aW9uOiByZWxhdGl2ZSAhaW1wb3J0YW50OwogICAgICB0cmFuc2l0aW9uOiBvcGFjaXR5IC4xNHMgZWFzZSwgZmlsdGVyIC4xNHMgZWFzZSwgYm9yZGVyLWNvbG9yIC4xNHMgZWFzZSAhaW1wb3J0YW50OwogICAgfQoKICAgIC5tZmRuLWNvbXBhdC1jYXJkLXYzLm1mZG4tZGV4LW9mZi12MyB7CiAgICAgIGZpbHRlcjogZ3JheXNjYWxlKC41NSkgc2F0dXJhdGUoLjI1KSAhaW1wb3J0YW50OwogICAgICBib3JkZXItY29sb3I6IHJnYmEoOTUsMTE4LDEyOCwuMTQpICFpbXBvcnRhbnQ7CiAgICB9CgogICAgLm1mZG4tY29tcGF0LWNhcmQtdjMubWZkbi1kZXgtb2ZmLXYzID4gKjpub3QoLm1mZG4tbm90ZS12MykgewogICAgICBvcGFjaXR5OiAuMzggIWltcG9ydGFudDsKICAgIH0KCiAgICAubWZkbi1jb21wYXQtY2FyZC12My5tZmRuLWh5YnJpZC12MyA+ICo6bm90KC5tZmRuLW5vdGUtdjMpIHsKICAgICAgb3BhY2l0eTogLjc4ICFpbXBvcnRhbnQ7CiAgICB9CgogICAgLm1mZG4tbm90ZS12MyB7CiAgICAgIGRpc3BsYXk6IGJsb2NrICFpbXBvcnRhbnQ7CiAgICAgIHdpZHRoOiAxMDAlICFpbXBvcnRhbnQ7CiAgICAgIG1hcmdpbi10b3A6IDdweCAhaW1wb3J0YW50OwogICAgICBwYWRkaW5nLXRvcDogNnB4ICFpbXBvcnRhbnQ7CiAgICAgIGJvcmRlci10b3A6IDFweCBzb2xpZCByZ2JhKDEwNSwxMzAsMTQwLC4xMCkgIWltcG9ydGFudDsKICAgICAgY29sb3I6ICM2NDdkODggIWltcG9ydGFudDsKICAgICAgZm9udC1zaXplOiA4LjVweCAhaW1wb3J0YW50OwogICAgICBsaW5lLWhlaWdodDogMS4yOCAhaW1wb3J0YW50OwogICAgICBsZXR0ZXItc3BhY2luZzogLjAyNWVtICFpbXBvcnRhbnQ7CiAgICAgIG9wYWNpdHk6IDEgIWltcG9ydGFudDsKICAgIH0KCiAgICAubWZkbi1oeWJyaWQtdjMgLm1mZG4tbm90ZS12MyB7CiAgICAgIGNvbG9yOiAjODM3OGFkICFpbXBvcnRhbnQ7CiAgICB9CgogICAgLm1mZG4tZGV4LW9mZi12MyBpbnB1dCwKICAgIC5tZmRuLWRleC1vZmYtdjMgc2VsZWN0LAogICAgLm1mZG4tZGV4LW9mZi12MyB0ZXh0YXJlYSwKICAgIC5tZmRuLWRleC1vZmYtdjMgYnV0dG9uLAogICAgLm1mZG4tZGV4LW9mZi12MyBbcm9sZT0ic3dpdGNoIl0sCiAgICAubWZkbi1kZXgtb2ZmLXYzIFtyb2xlPSJzbGlkZXIiXSwKICAgIC5tZmRuLWRleC1vZmYtdjMgW2NvbnRlbnRlZGl0YWJsZT0idHJ1ZSJdIHsKICAgICAgcG9pbnRlci1ldmVudHM6IG5vbmUgIWltcG9ydGFudDsKICAgIH0KICBgOwoKICBmdW5jdGlvbiBpbnN0YWxsU3R5bGUoKSB7CiAgICBpZiAoZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ21mZG4tc3R5bGUtdjMnKSkgcmV0dXJuOwogICAgY29uc3QgcyA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3N0eWxlJyk7CiAgICBzLmlkID0gJ21mZG4tc3R5bGUtdjMnOwogICAgcy50ZXh0Q29udGVudCA9IGNzczsKICAgIChkb2N1bWVudC5oZWFkIHx8IGRvY3VtZW50LmRvY3VtZW50RWxlbWVudCkuYXBwZW5kQ2hpbGQocyk7CiAgfQoKICBmdW5jdGlvbiB0ZXh0KGVsKSB7CiAgICByZXR1cm4gKGVsPy5pbm5lclRleHQgfHwgZWw/LnRleHRDb250ZW50IHx8ICcnKQogICAgICAucmVwbGFjZSgvXHMrL2csICcgJykKICAgICAgLnRyaW0oKTsKICB9CgogIGZ1bmN0aW9uIGxlYWZOb2Rlcyhyb290ID0gZG9jdW1lbnQuYm9keSkgewogICAgcmV0dXJuIEFycmF5LmZyb20ocm9vdC5xdWVyeVNlbGVjdG9yQWxsKCcqJykpLmZpbHRlcihlbCA9PiB7CiAgICAgIGlmIChlbC5pZCA9PT0gJ21mZG4tbmF0aXZlLXBsYXRmb3JtLXYzJykgcmV0dXJuIGZhbHNlOwogICAgICBpZiAoZWwuY2xhc3NMaXN0Py5jb250YWlucygnbWZkbi1ub3RlLXYzJykpIHJldHVybiBmYWxzZTsKICAgICAgaWYgKGVsLmNoaWxkcmVuLmxlbmd0aCkgcmV0dXJuIGZhbHNlOwogICAgICByZXR1cm4gQm9vbGVhbih0ZXh0KGVsKSk7CiAgICB9KTsKICB9CgogIGZ1bmN0aW9uIGxlYWZFeGFjdCh2YWx1ZSkgewogICAgY29uc3Qgd2FudGVkID0gU3RyaW5nKHZhbHVlKS50cmltKCkudG9Mb3dlckNhc2UoKTsKICAgIHJldHVybiBsZWFmTm9kZXMoKS5maW5kKGVsID0+IHRleHQoZWwpLnRvTG93ZXJDYXNlKCkgPT09IHdhbnRlZCkgfHwgbnVsbDsKICB9CgogIGZ1bmN0aW9uIGZpbmRQbGF0Zm9ybUNhcmQoKSB7CiAgICBjb25zdCBsYWJlbCA9IGxlYWZFeGFjdCgnUGxhdGZvcm0nKTsKICAgIGlmICghbGFiZWwpIHJldHVybiBudWxsOwoKICAgIGxldCBub2RlID0gbGFiZWwucGFyZW50RWxlbWVudDsKICAgIGxldCBiZXN0ID0gbnVsbDsKCiAgICBmb3IgKGxldCBkZXB0aCA9IDA7IG5vZGUgJiYgbm9kZSAhPT0gZG9jdW1lbnQuYm9keSAmJiBkZXB0aCA8IDc7IGRlcHRoKyssIG5vZGUgPSBub2RlLnBhcmVudEVsZW1lbnQpIHsKICAgICAgY29uc3QgdCA9IHRleHQobm9kZSkudG9Mb3dlckNhc2UoKTsKICAgICAgaWYgKCF0LmluY2x1ZGVzKCdwbGF0Zm9ybScpKSBjb250aW51ZTsKICAgICAgaWYgKHQuaW5jbHVkZXMoJ2FpIHBvbGljeScpIHx8IHQuaW5jbHVkZXMoJ2tpbGwgc3dpdGNoJykpIGJyZWFrOwoKICAgICAgY29uc3QgcmVjdCA9IG5vZGUuZ2V0Qm91bmRpbmdDbGllbnRSZWN0Py4oKTsKICAgICAgaWYgKCFyZWN0IHx8IHJlY3Qud2lkdGggPCA5MCB8fCByZWN0LmhlaWdodCA8IDQyIHx8IHJlY3QuaGVpZ2h0ID4gMTUwKSBjb250aW51ZTsKICAgICAgaWYgKHQubGVuZ3RoID4gMTIwKSBjb250aW51ZTsKCiAgICAgIGJlc3QgPSBub2RlOwoKICAgICAgY29uc3QgY3MgPSBnZXRDb21wdXRlZFN0eWxlKG5vZGUpOwogICAgICBpZiAocGFyc2VGbG9hdChjcy5ib3JkZXJUb3BXaWR0aCB8fCAnMCcpID4gMCkgYnJlYWs7CiAgICB9CgogICAgcmV0dXJuIGJlc3Q7CiAgfQoKICBmdW5jdGlvbiBmaW5kUGxhdGZvcm1WYWx1ZShjYXJkKSB7CiAgICBpZiAoIWNhcmQpIHJldHVybiBudWxsOwoKICAgIGNvbnN0IGxlYXZlcyA9IGxlYWZOb2RlcyhjYXJkKS5maWx0ZXIoZWwgPT4gdGV4dChlbCkudG9Mb3dlckNhc2UoKSAhPT0gJ3BsYXRmb3JtJyk7CiAgICBjb25zdCBrbm93biA9IGxlYXZlcy5maW5kKGVsID0+CiAgICAgIFsncHVtcC5mdW4nLCAncHVtcCcsICdkZXgnLCAnaHlicmlkJ10uaW5jbHVkZXModGV4dChlbCkudG9Mb3dlckNhc2UoKSkKICAgICk7CgogICAgcmV0dXJuIGtub3duIHx8IGxlYXZlc1tsZWF2ZXMubGVuZ3RoIC0gMV0gfHwgbnVsbDsKICB9CgogIGZ1bmN0aW9uIGxhYmVsKG1vZGUpIHsKICAgIHJldHVybiBtb2RlID09PSAncHVtcCcgPyAnUHVtcC5mdW4nCiAgICAgIDogbW9kZSA9PT0gJ2RleCcgPyAnREVYJwogICAgICA6IG1vZGUgPT09ICdoeWJyaWQnID8gJ0h5YnJpZCcKICAgICAgOiAn4oCUJzsKICB9CgogIGZ1bmN0aW9uIGNyZWF0ZU5hdGl2ZVNlbGVjdCgpIHsKICAgIGNvbnN0IHNlbGVjdCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3NlbGVjdCcpOwogICAgc2VsZWN0LmlkID0gJ21mZG4tbmF0aXZlLXBsYXRmb3JtLXYzJzsKICAgIHNlbGVjdC5zZXRBdHRyaWJ1dGUoJ2FyaWEtbGFiZWwnLCAnUGxhdGZvcm0nKTsKCiAgICBjb25zdCByb3dzID0gWwogICAgICBbJ3B1bXAnLCAnUHVtcC5mdW4nXSwKICAgICAgWydkZXgnLCAnREVYJ10sCiAgICAgIFsnaHlicmlkJywgJ0h5YnJpZCddCiAgICBdOwoKICAgIGZvciAoY29uc3QgW3ZhbHVlLCBuYW1lXSBvZiByb3dzKSB7CiAgICAgIGNvbnN0IG9wdGlvbiA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ29wdGlvbicpOwogICAgICBvcHRpb24udmFsdWUgPSB2YWx1ZTsKICAgICAgb3B0aW9uLnRleHRDb250ZW50ID0gbmFtZTsKICAgICAgc2VsZWN0LmFwcGVuZENoaWxkKG9wdGlvbik7CiAgICB9CgogICAgLy8gQ3JpdGljYWw6IHN0b3AgdGhlIG9sZCBjYXJkIGNsaWNrIGhhbmRsZXIgZnJvbSBldmVyIHNlZWluZyB0aGUgbmF0aXZlIHNlbGVjdCB0YXAuCiAgICBmb3IgKGNvbnN0IGV2ZW50TmFtZSBvZiBbJ3BvaW50ZXJkb3duJywgJ3RvdWNoc3RhcnQnLCAnbW91c2Vkb3duJywgJ2NsaWNrJ10pIHsKICAgICAgc2VsZWN0LmFkZEV2ZW50TGlzdGVuZXIoZXZlbnROYW1lLCBldiA9PiB7CiAgICAgICAgZXYuc3RvcFByb3BhZ2F0aW9uKCk7CiAgICAgIH0pOwogICAgfQoKICAgIHNlbGVjdC5hZGRFdmVudExpc3RlbmVyKCdjaGFuZ2UnLCBldiA9PiB7CiAgICAgIGV2LnN0b3BQcm9wYWdhdGlvbigpOwogICAgICBzd2l0Y2hNb2RlKHNlbGVjdC52YWx1ZSk7CiAgICB9KTsKCiAgICByZXR1cm4gc2VsZWN0OwogIH0KCiAgZnVuY3Rpb24gbW91bnRQbGF0Zm9ybSgpIHsKICAgIGNvbnN0IGNhcmQgPSBmaW5kUGxhdGZvcm1DYXJkKCk7CiAgICBpZiAoIWNhcmQpIHJldHVybiBmYWxzZTsKCiAgICBzdGF0ZS5jYXJkID0gY2FyZDsKICAgIHN0YXRlLnZhbHVlRWwgPSBmaW5kUGxhdGZvcm1WYWx1ZShjYXJkKTsKCiAgICBjYXJkLmNsYXNzTGlzdC5hZGQoJ21mZG4tcGxhdGZvcm0tY2FyZC12MycpOwoKICAgIC8vIFJlbW92ZSBhbnkgc3RhbGUgVjMgc2VsZWN0IGNhdXNlZCBieSBhIHNldHRpbmdzIHJlLXJlbmRlci4KICAgIGNvbnN0IGN1cnJlbnQgPSBjYXJkLnF1ZXJ5U2VsZWN0b3IoJyNtZmRuLW5hdGl2ZS1wbGF0Zm9ybS12MycpOwogICAgaWYgKGN1cnJlbnQpIHsKICAgICAgc3RhdGUuc2VsZWN0ID0gY3VycmVudDsKICAgIH0gZWxzZSB7CiAgICAgIHN0YXRlLnNlbGVjdCA9IGNyZWF0ZU5hdGl2ZVNlbGVjdCgpOwogICAgICBjYXJkLmFwcGVuZENoaWxkKHN0YXRlLnNlbGVjdCk7CiAgICB9CgogICAgdXBkYXRlVmlzaWJsZVBsYXRmb3JtKCk7CiAgICByZXR1cm4gdHJ1ZTsKICB9CgogIGZ1bmN0aW9uIHVwZGF0ZVZpc2libGVQbGF0Zm9ybSgpIHsKICAgIGlmICghc3RhdGUuY2FyZD8uaXNDb25uZWN0ZWQpIG1vdW50UGxhdGZvcm0oKTsKCiAgICBzdGF0ZS52YWx1ZUVsID0gZmluZFBsYXRmb3JtVmFsdWUoc3RhdGUuY2FyZCk7CgogICAgaWYgKHN0YXRlLnZhbHVlRWwgJiYgc3RhdGUubW9kZSkgewogICAgICBzdGF0ZS52YWx1ZUVsLnRleHRDb250ZW50ID0gbGFiZWwoc3RhdGUubW9kZSk7CiAgICB9CgogICAgaWYgKHN0YXRlLnNlbGVjdCAmJiBzdGF0ZS5tb2RlICYmIHN0YXRlLnNlbGVjdC52YWx1ZSAhPT0gc3RhdGUubW9kZSkgewogICAgICBzdGF0ZS5zZWxlY3QudmFsdWUgPSBzdGF0ZS5tb2RlOwogICAgfQoKICAgIGlmIChzdGF0ZS5zZWxlY3QpIHN0YXRlLnNlbGVjdC5kaXNhYmxlZCA9IHN0YXRlLmJ1c3k7CiAgICBzdGF0ZS5jYXJkPy5jbGFzc0xpc3QudG9nZ2xlKCdtZmRuLWJ1c3ktdjMnLCBzdGF0ZS5idXN5KTsKICB9CgogIGZ1bmN0aW9uIHJ1bGVGb3IocykgewogICAgY29uc3QgdCA9IFN0cmluZyhzIHx8ICcnKS5yZXBsYWNlKC9ccysvZywgJyAnKS50cmltKCk7CiAgICByZXR1cm4gUFVNUF9PTkxZLmZpbmQocnVsZSA9PiBydWxlLnRlc3QodCkpIHx8IG51bGw7CiAgfQoKICBmdW5jdGlvbiBmaWVsZENhcmRGcm9tTGVhZihsZWFmKSB7CiAgICBsZXQgbm9kZSA9IGxlYWY/LnBhcmVudEVsZW1lbnQ7CiAgICBsZXQgZmFsbGJhY2sgPSBudWxsOwoKICAgIGZvciAobGV0IGRlcHRoID0gMDsgbm9kZSAmJiBub2RlICE9PSBkb2N1bWVudC5ib2R5ICYmIGRlcHRoIDwgNzsgZGVwdGgrKywgbm9kZSA9IG5vZGUucGFyZW50RWxlbWVudCkgewogICAgICBpZiAobm9kZSA9PT0gc3RhdGUuY2FyZCkgcmV0dXJuIG51bGw7CgogICAgICBjb25zdCB0ID0gdGV4dChub2RlKTsKICAgICAgaWYgKHQubGVuZ3RoID4gMzYwKSBicmVhazsKCiAgICAgIGNvbnN0IHJlY3QgPSBub2RlLmdldEJvdW5kaW5nQ2xpZW50UmVjdD8uKCk7CiAgICAgIGlmICghcmVjdCB8fCByZWN0LndpZHRoIDwgMTAwIHx8IHJlY3QuaGVpZ2h0IDwgNDIgfHwgcmVjdC5oZWlnaHQgPiAyNDApIGNvbnRpbnVlOwoKICAgICAgY29uc3QgY29udHJvbHMgPSBub2RlLnF1ZXJ5U2VsZWN0b3JBbGwoCiAgICAgICAgJ2lucHV0LHNlbGVjdCx0ZXh0YXJlYSxidXR0b24sW3JvbGU9InN3aXRjaCJdLFtyb2xlPSJzbGlkZXIiXSxbY29udGVudGVkaXRhYmxlPSJ0cnVlIl0nCiAgICAgICkubGVuZ3RoOwoKICAgICAgY29uc3QgY3MgPSBnZXRDb21wdXRlZFN0eWxlKG5vZGUpOwogICAgICBjb25zdCBib3JkZXJlZCA9CiAgICAgICAgcGFyc2VGbG9hdChjcy5ib3JkZXJUb3BXaWR0aCB8fCAnMCcpID4gMCB8fAogICAgICAgIHBhcnNlRmxvYXQoY3MuYm9yZGVyTGVmdFdpZHRoIHx8ICcwJykgPiAwOwoKICAgICAgaWYgKCFmYWxsYmFjayAmJiB0Lmxlbmd0aCA8IDIyMCkgZmFsbGJhY2sgPSBub2RlOwogICAgICBpZiAoYm9yZGVyZWQgJiYgY29udHJvbHMgPD0gNCAmJiB0Lmxlbmd0aCA8IDI3MCkgcmV0dXJuIG5vZGU7CiAgICB9CgogICAgcmV0dXJuIGZhbGxiYWNrOwogIH0KCiAgZnVuY3Rpb24gYmxvY2tJbmFjdGl2ZShldikgewogICAgY29uc3QgY2FyZCA9IGV2LmN1cnJlbnRUYXJnZXQ7CiAgICBpZiAoIWNhcmQuY2xhc3NMaXN0LmNvbnRhaW5zKCdtZmRuLWRleC1vZmYtdjMnKSkgcmV0dXJuOwogICAgZXYucHJldmVudERlZmF1bHQoKTsKICAgIGV2LnN0b3BJbW1lZGlhdGVQcm9wYWdhdGlvbigpOwogIH0KCiAgZnVuY3Rpb24gaW5zdGFsbEJsb2NrZXIoY2FyZCkgewogICAgaWYgKGNhcmQuZGF0YXNldC5tZmRuQmxvY2tlclYzID09PSAnMScpIHJldHVybjsKICAgIGNhcmQuZGF0YXNldC5tZmRuQmxvY2tlclYzID0gJzEnOwoKICAgIGZvciAoY29uc3QgZXZlbnROYW1lIG9mIFsKICAgICAgJ3BvaW50ZXJkb3duJywgJ3RvdWNoc3RhcnQnLCAnbW91c2Vkb3duJywgJ2NsaWNrJywKICAgICAgJ2tleWRvd24nLCAnaW5wdXQnLCAnY2hhbmdlJwogICAgXSkgewogICAgICBjYXJkLmFkZEV2ZW50TGlzdGVuZXIoZXZlbnROYW1lLCBibG9ja0luYWN0aXZlLCB0cnVlKTsKICAgIH0KICB9CgogIGZ1bmN0aW9uIGNsZWFyQ29tcGF0aWJpbGl0eSgpIHsKICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoJy5tZmRuLWNvbXBhdC1jYXJkLXYzJykuZm9yRWFjaChjYXJkID0+IHsKICAgICAgY2FyZC5jbGFzc0xpc3QucmVtb3ZlKAogICAgICAgICdtZmRuLWNvbXBhdC1jYXJkLXYzJywKICAgICAgICAnbWZkbi1kZXgtb2ZmLXYzJywKICAgICAgICAnbWZkbi1oeWJyaWQtdjMnCiAgICAgICk7CiAgICAgIGNhcmQucmVtb3ZlQXR0cmlidXRlKCdhcmlhLWRpc2FibGVkJyk7CiAgICAgIGNhcmQucXVlcnlTZWxlY3RvcignOnNjb3BlID4gLm1mZG4tbm90ZS12MycpPy5yZW1vdmUoKTsKICAgIH0pOwogIH0KCiAgZnVuY3Rpb24gYXBwbHlDb21wYXRpYmlsaXR5KCkgewogICAgY2xlYXJUaW1lb3V0KHN0YXRlLmNvbXBhdFRpbWVyKTsKCiAgICBzdGF0ZS5jb21wYXRUaW1lciA9IHNldFRpbWVvdXQoKCkgPT4gewogICAgICBjbGVhckNvbXBhdGliaWxpdHkoKTsKICAgICAgaWYgKCFzdGF0ZS5tb2RlIHx8IHN0YXRlLm1vZGUgPT09ICdwdW1wJykgcmV0dXJuOwoKICAgICAgY29uc3Qgc2VlbiA9IG5ldyBTZXQoKTsKCiAgICAgIGZvciAoY29uc3QgbGVhZiBvZiBsZWFmTm9kZXMoKSkgewogICAgICAgIGNvbnN0IHQgPSB0ZXh0KGxlYWYpOwogICAgICAgIGlmICh0Lmxlbmd0aCA+IDExMCkgY29udGludWU7CgogICAgICAgIGNvbnN0IHJ1bGUgPSBydWxlRm9yKHQpOwogICAgICAgIGlmICghcnVsZSkgY29udGludWU7CgogICAgICAgIGNvbnN0IGNhcmQgPSBmaWVsZENhcmRGcm9tTGVhZihsZWFmKTsKICAgICAgICBpZiAoIWNhcmQgfHwgc2Vlbi5oYXMoY2FyZCkpIGNvbnRpbnVlOwogICAgICAgIHNlZW4uYWRkKGNhcmQpOwoKICAgICAgICBjYXJkLmNsYXNzTGlzdC5hZGQoJ21mZG4tY29tcGF0LWNhcmQtdjMnKTsKCiAgICAgICAgY29uc3Qgbm90ZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2RpdicpOwogICAgICAgIG5vdGUuY2xhc3NOYW1lID0gJ21mZG4tbm90ZS12Myc7CgogICAgICAgIGlmIChzdGF0ZS5tb2RlID09PSAnZGV4JykgewogICAgICAgICAgY2FyZC5jbGFzc0xpc3QuYWRkKCdtZmRuLWRleC1vZmYtdjMnKTsKICAgICAgICAgIGNhcmQuc2V0QXR0cmlidXRlKCdhcmlhLWRpc2FibGVkJywgJ3RydWUnKTsKICAgICAgICAgIG5vdGUudGV4dENvbnRlbnQgPSBydWxlLmRleDsKICAgICAgICAgIGluc3RhbGxCbG9ja2VyKGNhcmQpOwogICAgICAgIH0gZWxzZSB7CiAgICAgICAgICBjYXJkLmNsYXNzTGlzdC5hZGQoJ21mZG4taHlicmlkLXYzJyk7CiAgICAgICAgICBub3RlLnRleHRDb250ZW50ID0gcnVsZS5oeWJyaWQ7CiAgICAgICAgfQoKICAgICAgICBjYXJkLmFwcGVuZENoaWxkKG5vdGUpOwogICAgICB9CiAgICB9LCA2MCk7CiAgfQoKICBmdW5jdGlvbiByZW5kZXIoKSB7CiAgICB1cGRhdGVWaXNpYmxlUGxhdGZvcm0oKTsKICAgIGFwcGx5Q29tcGF0aWJpbGl0eSgpOwogIH0KCiAgYXN5bmMgZnVuY3Rpb24gbG9hZFN0YXR1cygpIHsKICAgIGlmIChkb2N1bWVudC5oaWRkZW4pIHJldHVybjsKCiAgICB0cnkgewogICAgICBjb25zdCByID0gYXdhaXQgZmV0Y2goJy9hcGkvZGlzY292ZXJ5LXNvdXJjZScsIHsKICAgICAgICBtZXRob2Q6ICdHRVQnLAogICAgICAgIGNhY2hlOiAnbm8tc3RvcmUnLAogICAgICAgIGNyZWRlbnRpYWxzOiAnc2FtZS1vcmlnaW4nLAogICAgICAgIGhlYWRlcnM6IHthY2NlcHQ6ICdhcHBsaWNhdGlvbi9qc29uJ30KICAgICAgfSk7CgogICAgICBjb25zdCBqID0gYXdhaXQgci5qc29uKCkuY2F0Y2goKCkgPT4gKHt9KSk7CiAgICAgIGlmICghci5vaykgdGhyb3cgbmV3IEVycm9yKGo/Lm1lc3NhZ2UgfHwgaj8uZXJyb3IgfHwgYEhUVFAgJHtyLnN0YXR1c31gKTsKCiAgICAgIHN0YXRlLm1vZGUgPSBTdHJpbmcoaj8uc291cmNlPy5tb2RlIHx8ICcnKS50b0xvd2VyQ2FzZSgpIHx8IHN0YXRlLm1vZGU7CiAgICAgIHJlbmRlcigpOwogICAgfSBjYXRjaCAoZSkgewogICAgICBjb25zb2xlLndhcm4oJ1tESVNDT1ZFUlkgTkFUSVZFIFYzXSBzdGF0dXM6JywgZT8ubWVzc2FnZSB8fCBlKTsKICAgIH0KICB9CgogIGFzeW5jIGZ1bmN0aW9uIHN3aXRjaE1vZGUobW9kZSkgewogICAgbW9kZSA9IFN0cmluZyhtb2RlIHx8ICcnKS50b0xvd2VyQ2FzZSgpOwoKICAgIGlmICghWydwdW1wJywgJ2RleCcsICdoeWJyaWQnXS5pbmNsdWRlcyhtb2RlKSB8fCBzdGF0ZS5idXN5KSB7CiAgICAgIHVwZGF0ZVZpc2libGVQbGF0Zm9ybSgpOwogICAgICByZXR1cm47CiAgICB9CgogICAgaWYgKG1vZGUgPT09IHN0YXRlLm1vZGUpIHsKICAgICAgdXBkYXRlVmlzaWJsZVBsYXRmb3JtKCk7CiAgICAgIHJldHVybjsKICAgIH0KCiAgICBjb25zdCBwcmV2aW91cyA9IHN0YXRlLm1vZGU7CiAgICBzdGF0ZS5tb2RlID0gbW9kZTsKICAgIHN0YXRlLmJ1c3kgPSB0cnVlOwogICAgcmVuZGVyKCk7CgogICAgdHJ5IHsKICAgICAgY29uc3QgciA9IGF3YWl0IGZldGNoKCcvYXBpL2Rpc2NvdmVyeS1zb3VyY2UnLCB7CiAgICAgICAgbWV0aG9kOiAnUE9TVCcsCiAgICAgICAgY2FjaGU6ICduby1zdG9yZScsCiAgICAgICAgY3JlZGVudGlhbHM6ICdzYW1lLW9yaWdpbicsCiAgICAgICAgaGVhZGVyczogewogICAgICAgICAgJ2NvbnRlbnQtdHlwZSc6ICdhcHBsaWNhdGlvbi9qc29uJywKICAgICAgICAgIGFjY2VwdDogJ2FwcGxpY2F0aW9uL2pzb24nCiAgICAgICAgfSwKICAgICAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7bW9kZX0pCiAgICAgIH0pOwoKICAgICAgY29uc3QgaiA9IGF3YWl0IHIuanNvbigpLmNhdGNoKCgpID0+ICh7fSkpOwogICAgICBpZiAoIXIub2spIHRocm93IG5ldyBFcnJvcihqPy5tZXNzYWdlIHx8IGo/LmVycm9yIHx8IGBIVFRQICR7ci5zdGF0dXN9YCk7CgogICAgICBzdGF0ZS5tb2RlID0gU3RyaW5nKGo/LnNvdXJjZT8ubW9kZSB8fCBtb2RlKS50b0xvd2VyQ2FzZSgpOwogICAgfSBjYXRjaCAoZSkgewogICAgICBzdGF0ZS5tb2RlID0gcHJldmlvdXM7CiAgICAgIGNvbnNvbGUuZXJyb3IoJ1tESVNDT1ZFUlkgTkFUSVZFIFYzXSBzd2l0Y2ggZmFpbGVkOicsIGUpOwogICAgfSBmaW5hbGx5IHsKICAgICAgc3RhdGUuYnVzeSA9IGZhbHNlOwogICAgICByZW5kZXIoKTsKICAgICAgc2V0VGltZW91dChsb2FkU3RhdHVzLCA0MDApOwogICAgfQogIH0KCiAgZnVuY3Rpb24gcXVldWVSZWZyZXNoKCkgewogICAgY2xlYXJUaW1lb3V0KHN0YXRlLnJlZnJlc2hUaW1lcik7CiAgICBzdGF0ZS5yZWZyZXNoVGltZXIgPSBzZXRUaW1lb3V0KCgpID0+IHsKICAgICAgbW91bnRQbGF0Zm9ybSgpOwogICAgICBhcHBseUNvbXBhdGliaWxpdHkoKTsKICAgIH0sIDcwKTsKICB9CgogIGZ1bmN0aW9uIHN0YXJ0KCkgewogICAgaW5zdGFsbFN0eWxlKCk7CgogICAgLy8gQW55IG9sZCBjdXN0b20gZHJvcGRvd24gbGVmdCBpbiB0aGUgbGl2ZSBET00gaXMgcmVtb3ZlZCBpbW1lZGlhdGVseS4KICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdtZmR4LXBsYXRmb3JtLW1lbnUtdjInKT8ucmVtb3ZlPy4oKTsKICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdtZmRzLXBhbmVsLXYxJyk/LnJlbW92ZT8uKCk7CgogICAgbW91bnRQbGF0Zm9ybSgpOwogICAgbG9hZFN0YXR1cygpOwoKICAgIHN0YXRlLm9ic2VydmVyID0gbmV3IE11dGF0aW9uT2JzZXJ2ZXIocXVldWVSZWZyZXNoKTsKICAgIHN0YXRlLm9ic2VydmVyLm9ic2VydmUoZG9jdW1lbnQuYm9keSwgewogICAgICBjaGlsZExpc3Q6IHRydWUsCiAgICAgIHN1YnRyZWU6IHRydWUKICAgIH0pOwoKICAgIHN0YXRlLnBvbGwgPSBzZXRJbnRlcnZhbChsb2FkU3RhdHVzLCAyNTAwKTsKCiAgICBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyKCd2aXNpYmlsaXR5Y2hhbmdlJywgKCkgPT4gewogICAgICBpZiAoIWRvY3VtZW50LmhpZGRlbikgewogICAgICAgIG1vdW50UGxhdGZvcm0oKTsKICAgICAgICBsb2FkU3RhdHVzKCk7CiAgICAgIH0KICAgIH0pOwogIH0KCiAgaWYgKGRvY3VtZW50LnJlYWR5U3RhdGUgPT09ICdsb2FkaW5nJykgewogICAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignRE9NQ29udGVudExvYWRlZCcsIHN0YXJ0LCB7b25jZTogdHJ1ZX0pOwogIH0gZWxzZSB7CiAgICBzdGFydCgpOwogIH0KfSkoKTsK").decode("utf-8")

def log(msg):
    print("[DISCOVERY-NATIVE-V3] " + str(msg), flush=True)

def find_root():
    candidates = [
        Path.cwd(),
        Path.cwd() / "memeflow-app",
        Path.home() / "workspace",
        Path.home() / "workspace" / "memeflow-app",
        Path("/home/runner/workspace"),
        Path("/home/runner/workspace/memeflow-app"),
    ]
    for root in candidates:
        try:
            root = root.resolve()
        except Exception:
            continue
        if (root / "system.js").is_file() and (root / "app-server.mjs").is_file():
            return root

    for base in [Path("/home/runner/workspace"), Path.cwd()]:
        if not base.exists():
            continue
        for p in base.glob("**/system.js"):
            if (p.parent / "app-server.mjs").is_file():
                return p.parent.resolve()

    raise RuntimeError("MEMEFLOW system.js/app-server.mjs root not found")

ROOT = find_root()
SYSTEM = ROOT / "system.js"
SERVER = ROOT / "app-server.mjs"
BACKUP = ROOT / (".discovery-native-v3-backup-" + STAMP)
BACKUP.mkdir(parents=True, exist_ok=True)
changed = []

def rel(path):
    return path.resolve().relative_to(ROOT.resolve())

def backup(path):
    if path in changed:
        return
    dst = BACKUP / rel(path)
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, dst)
    changed.append(path)

def write(path, data):
    backup(path)
    path.write_text(data, encoding="utf-8")
    log("patched " + str(rel(path)))

def rollback(reason):
    log("ERROR: " + str(reason))
    for path in reversed(changed):
        src = BACKUP / rel(path)
        if src.exists():
            shutil.copy2(src, path)
            log("restored " + str(rel(path)))
    log("ROLLBACK COMPLETE")
    sys.exit(1)

def remove_old_v2_if_safe(text):
    marker = "// " + OLD_V2
    start = text.find(marker)
    if start < 0:
        return text, False

    tail = text[start:]

    # V2 was installed as an appended final IIFE. Remove it only when it is
    # demonstrably the final patch region; otherwise leave it and V3 neutralizes
    # its DOM/CSS at runtime instead of risking project code.
    if "window.__mfDiscoveryPlatformDropdownV2" not in tail:
        return text, False

    end = tail.rfind("})();")
    if end < 0:
        return text, False

    suffix = tail[end + len("})();"):]

    if suffix.strip():
        return text, False

    return text[:start].rstrip() + "\n", True

try:
    log("root: " + str(ROOT))

    server = SERVER.read_text(encoding="utf-8")
    if "/api/discovery-source" not in server:
        raise RuntimeError(
            "Discovery Router V1.1 is not present: /api/discovery-source missing"
        )

    text = SYSTEM.read_text(encoding="utf-8")

    if PATCH_ID in text:
        log("V3 already installed")
        sys.exit(0)

    text, removed = remove_old_v2_if_safe(text)

    if removed:
        log("removed old custom V2 dropdown completely")
    else:
        log("V2 source was not safely removable; V3 will neutralize it in DOM")

    text = (
        text.rstrip()
        + "\n\n// " + PATCH_ID + "\n"
        + RUNTIME
        + "\n"
    )

    write(SYSTEM, text)

    check = subprocess.run(
        ["node", "--check", str(SYSTEM)],
        cwd=ROOT,
        capture_output=True,
        text=True
    )

    if check.returncode != 0:
        raise RuntimeError(
            "node --check system.js failed:\n"
            + (check.stderr or check.stdout)
        )

    final = SYSTEM.read_text(encoding="utf-8")

    for token in [
        PATCH_ID,
        "mfdn-native-platform-v3",
        "<select",
        "/api/discovery-source",
        "Pump.fun",
        "Hybrid",
        "mfdn-dex-off-v3"
    ]:
        # `<select` exists only in DOM at runtime, so validate createElement instead.
        if token == "<select":
            token = "createElement('select')"
        if token not in final:
            raise RuntimeError("validation missing: " + token)

    log("system.js syntax OK")
    log("INSTALL COMPLETE")
    log("PLATFORM now uses a native HTML select like the other iOS settings")
    log("iPhone/Safari will show its native system picker")
    log("options: Pump.fun / DEX / Hybrid")
    log("old custom V2 dropdown is removed or neutralized")
    log("DEX-only compatibility dimming is preserved")
    log("HYBRID compatibility notes are preserved")
    log("backup: " + str(BACKUP))
    log("Hard-refresh System settings.")

except Exception as exc:
    rollback(exc)
