import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import zlib from 'node:zlib';import {fileURLToPath} from 'node:url';
import {JsonStore,sessionId,defaults} from './src/store.mjs';import {RpcPool,validPubkey,decodeCurve,decodeCreateData} from './src/solana.mjs';import {evaluate} from './src/evaluate.mjs';import {StripeBilling} from './src/billing.mjs';
const root=path.dirname(fileURLToPath(import.meta.url)),dataDir=path.resolve(root,process.env.DATA_DIR||'data'),store=new JsonStore(dataDir);
const billing=new StripeBilling({store,secretKey:process.env.STRIPE_SECRET_KEY,priceId:process.env.STRIPE_PRICE_ID,webhookSecret:process.env.STRIPE_WEBHOOK_SECRET,apiBase:process.env.STRIPE_API_BASE});
const rpcUrls=(process.env.SOLANA_RPC_URLS||'').split(',').map(x=>x.trim()).filter(Boolean),wsUrls=(process.env.SOLANA_WS_URLS||'').split(',').map(x=>x.trim()).filter(Boolean);const rpc=new RpcPool(rpcUrls,process.env.SOLANA_COMMITMENT||'confirmed');
const PUMP='6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P',ALLOW_ANON=process.env.ALLOW_ANONYMOUS_PAPER!=='false';
const OWNER_ACCESS_KEY=process.env.OWNER_ACCESS_KEY||'';
const OWNER_USER_IDS=new Set((process.env.OWNER_USER_IDS||'').split(',').map(x=>x.trim()).filter(Boolean));
let discovery={connected:false,url:null,lastEventAt:null,reconnects:0,error:null,startedAt:Date.now()},ws=null,wsTimer=null;const streams=new Map(),priceTimers=new Map(),tradeWindows=new Map();
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
function user(req,res){let id=cookies(req).mf_session;if(!id&&ALLOW_ANON){id=sessionId();res.setHeader('Set-Cookie',`mf_session=${encodeURIComponent(id)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000`)}return id?store.user(id):null}
function json(res,status,obj){res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(obj))}
async function rawBody(req,limit=1e6){const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>limit)throw Error('body too large');chunks.push(c)}return Buffer.concat(chunks).toString('utf8')}
async function body(req){const s=await rawBody(req);return s?JSON.parse(s):{}}
function origin(req){if(process.env.APP_URL||process.env.APP_BASE_URL)return (process.env.APP_URL||process.env.APP_BASE_URL).replace(/\/$/,'');const proto=(req.headers['x-forwarded-proto']||'http').split(',')[0].trim();const host=(req.headers['x-forwarded-host']||req.headers.host||'localhost').split(',')[0].trim();return `${proto}://${host}`}
function hasLiveEntitlement(u){return Boolean(u?.isOwner||u?.liveEntitled)}
function billingStatus(u){const owner=Boolean(u.isOwner);const stripe=Boolean(u.liveEntitled);return {plan:owner?'owner':(u.plan||'free'),subscriptionStatus:owner?'owner_grant':(u.subscriptionStatus||'free'),liveEntitled:owner||stripe,entitlementSource:owner?'owner':(stripe?'stripe':'none'),isOwner:owner,price:49.99,currency:'USD',stripeCustomerId:u.stripeCustomerId||null,currentPeriodEnd:owner?null:(u.currentPeriodEnd||null),cancelAtPeriodEnd:owner?false:Boolean(u.cancelAtPeriodEnd)}}
function candidateView(d){const t=store.state.tokens[d.mint]||{};return {id:d.mint,mint:d.mint,name:t.name||t.symbol||d.mint.slice(0,6),symbol:t.symbol||'TOKEN',state:d.state,score:d.score,confidence:d.confidence,data:Math.round((t.dataQuality||0)*100),lane:d.state==='BUY READY'?'READY':'QUEUE',priority:d.score,meta:t.source||'Solana on-chain',price:t.priceSol,marketCap:t.marketCapSol?`${t.marketCapSol.toFixed(2)} SOL`:'—',holders:t.holderCount,top10:t.top10Pct,developer:t.developerPct,buyPressure:t.buyPressure,evidence:{'Mint':d.mint,'Price (SOL)':t.priceSol??'—','Liquidity (SOL)':t.liquiditySol??'—','Holders':t.holderCount??'—','Top 10':t.top10Pct!=null?t.top10Pct.toFixed(2)+'%':'—','Developer':t.developerPct!=null?t.developerPct.toFixed(2)+'%':'—','Buy pressure':t.buyPressure!=null?t.buyPressure.toFixed(2)+'×':'—','Source':t.source||'Solana'},timeline:t.timeline||[],primaryReason:d.primaryReason,reasons:d.reasons,riskApproved:d.state==='BUY READY',routeApproved:d.priceSol!=null,holderFresh:t.holderFresh,positionSize:null,quoteAgeMs:Date.now()-(t.updatedAt||0),slippagePct:null}}
function evaluateAll(token){for(const uid of Object.keys(store.state.users)){const d=evaluate(token,store.settings(uid));store.setDecision(uid,token.mint,{...d,primaryReason:d.primaryReason})}}
async function enrich(mint,curve){try{const [supply,largest,curveInfo]=await Promise.all([rpc.call('getTokenSupply',[mint,{commitment:'confirmed'}]),rpc.call('getTokenLargestAccounts',[mint,{commitment:'confirmed'}]),curve?rpc.call('getAccountInfo',[curve,{encoding:'base64',commitment:'confirmed'}]):Promise.resolve(null)]);const decimals=supply.value.decimals,total=Number(supply.value.uiAmountString||0),vals=(largest.value||[]).map(x=>Number(x.uiAmountString||0));const top10=total?vals.slice(0,10).reduce((a,b)=>a+b,0)/total*100:null;let c={};if(curveInfo?.value?.data?.[0])c=decodeCurve(curveInfo.value.data[0],decimals);const tw=tradeWindows.get(mint)||{buy:0,sell:0};const token=store.setToken(mint,{decimals,totalSupply:total,top10Pct:top10,holderCount:vals.length===20?null:vals.filter(v=>v>0).length,holderFresh:true,priceSol:c.priceSol??null,liquiditySol:c.liquiditySol??null,marketCapSol:c.priceSol?c.priceSol*total:null,complete:c.complete??null,buyPressure:tw.sell?tw.buy/tw.sell:tw.buy?tw.buy:null,dataQuality:[total,top10,c.priceSol].filter(x=>x!=null).length/3,source:'Solana RPC',lastScannedAt:Date.now()});evaluateAll(token);publish(mint);ensurePriceTimer(mint,curve)}catch(e){store.state.metrics.errors++;store.setToken(mint,{scanError:e.message,holderFresh:false});store.save()}}
function publish(mint){const rows=store.tokens();const t=store.state.tokens[mint];for(const res of streams.get(mint)||[]){res.write(`event: update\ndata: ${JSON.stringify({point:t?.priceSol?{t:Date.now(),price:t.priceSol,source:'Solana'}:null,status:{stale:!t?.priceSol,error:t?.scanError||null,source:t?.source}})}\n\n`)}}
function ensurePriceTimer(mint,curve){if(priceTimers.has(mint)||!curve)return;const timer=setInterval(async()=>{const t=store.state.tokens[mint];if(Date.now()-(t?.updatedAt||0)>600000&&(streams.get(mint)?.size||0)===0){clearInterval(timer);priceTimers.delete(mint);return}try{const info=await rpc.call('getAccountInfo',[curve,{encoding:'base64',commitment:'confirmed'}]);if(info?.value?.data?.[0]){const c=decodeCurve(info.value.data[0],t.decimals||6);store.setToken(mint,{priceSol:c.priceSol,liquiditySol:c.liquiditySol,complete:c.complete,source:'Solana bonding curve'});publish(mint)}}catch(e){store.setToken(mint,{scanError:e.message})}},Math.max(1000,Number(process.env.POLL_ACTIVE_MS||2000)));priceTimers.set(mint,timer)}
async function processSignature(sig){const tx=await rpc.call('getTransaction',[sig,{encoding:'jsonParsed',commitment:'confirmed',maxSupportedTransactionVersion:0}]);if(!tx)return;const msg=tx.transaction.message,keys=(msg.accountKeys||[]).map(x=>typeof x==='string'?x:x.pubkey),all=[...(msg.instructions||[]),...((tx.meta?.innerInstructions||[]).flatMap(x=>x.instructions||[]))];for(const ix of all){const pid=typeof ix.programId==='string'?ix.programId:keys[ix.programIdIndex];if(pid!==PUMP)continue;const parsed=ix.data?decodeCreateData(ix.data):null;if(parsed){const ac=(ix.accounts||[]).map(a=>typeof a==='number'?keys[a]:a);const mint=ac[0],curve=ac[2];if(validPubkey(mint)){store.addToken({mint,curve,name:parsed.name,symbol:parsed.symbol,uri:parsed.uri,creator:ac[7]||null,discoveredAt:Date.now(),slot:tx.slot,signature:sig,source:'Pump create'});await enrich(mint,curve)}}else{const logs=tx.meta?.logMessages||[],buy=logs.some(x=>/Instruction: Buy/i.test(x)),sell=logs.some(x=>/Instruction: Sell/i.test(x));if(buy||sell){for(const mint of Object.keys(store.state.tokens)){if(keys.includes(mint)){const w=tradeWindows.get(mint)||{buy:0,sell:0};if(buy)w.buy++;if(sell)w.sell++;tradeWindows.set(mint,w);break}}}}}}
function startDiscovery(i=0){if(process.env.DISCOVERY_ENABLED==='false'||!wsUrls.length){discovery.error='SOLANA_WS_URLS not configured';return}const url=wsUrls[i%wsUrls.length];try{ws=new WebSocket(url);discovery.url=url;ws.onopen=()=>{discovery.connected=true;discovery.error=null;ws.send(JSON.stringify({jsonrpc:'2.0',id:1,method:'logsSubscribe',params:[{mentions:[PUMP]},{commitment:'confirmed'}]}))};ws.onmessage=ev=>{try{const m=JSON.parse(ev.data);const sig=m.params?.result?.value?.signature;if(sig){discovery.lastEventAt=Date.now();processSignature(sig).catch(e=>discovery.error=e.message)}}catch{}};ws.onerror=()=>{};ws.onclose=()=>{discovery.connected=false;discovery.reconnects++;clearTimeout(wsTimer);wsTimer=setTimeout(()=>startDiscovery(i+1),Math.min(30000,1000*2**Math.min(discovery.reconnects,5)))}}catch(e){discovery.error=e.message;wsTimer=setTimeout(()=>startDiscovery(i+1),5000)}}
startDiscovery();
async function handler(req,res){const url=new URL(req.url,'http://x');
 if(url.pathname==='/api/billing/webhook'&&req.method==='POST'){const raw=await rawBody(req);try{billing.verify(raw,req.headers['stripe-signature']);const result=billing.processEvent(JSON.parse(raw));return json(res,200,{received:true,...result})}catch(e){return json(res,e.code==='BAD_SIGNATURE'?400:500,{error:e.code||'WEBHOOK_ERROR',message:e.message})}}
 const u=user(req,res);if(u&&OWNER_USER_IDS.has(u.id)&&!u.isOwner)store.grantOwner(u.id,'owner_user_ids');
 if(url.pathname==='/api/health')return json(res,200,{ok:true,server:'online',version:'1.0.1-clean',timestamp:new Date().toISOString()});
 if(url.pathname==='/api/market/status')return json(res,200,{ok:true,backend:'online',database:'online',rpc:rpc.last.ok?'online':(rpcUrls.length?'temporarily_unavailable':'not_configured'),discovery:discovery.connected?'online':(wsUrls.length?'connecting':'not_configured'),decisionEngine:'online',billing:billing.configured?'configured':'not_configured',updatedAt:new Date().toISOString()});if(url.pathname==='/api/system/health'){let slot=null,block=null;try{[slot,block]=await Promise.all([rpc.call('getSlot',[{commitment:'confirmed'}]),rpc.call('getBlockHeight',[{commitment:'confirmed'}])])}catch{}return json(res,200,{status:rpc.last.ok?'HEALTHY':'UNAVAILABLE',components:{primaryRpc:{status:rpc.last.ok?'HEALTHY':'UNAVAILABLE',latencyMs:rpc.last.latency},backupRpc:{status:rpcUrls.length>1?'STANDBY':'NOT CONFIGURED'},pumpDiscovery:{status:discovery.connected?'LIVE':'UNAVAILABLE',lastEventAt:discovery.lastEventAt},marketIndexer:{status:'LIVE',scanned:store.state.metrics.scanned},candleBuilder:{status:'LIVE'},decisionEngine:{status:'LIVE'},authentication:{status:ALLOW_ANON?'ANONYMOUS PAPER':'REQUIRED'},billing:{status:billing.configured?'CONFIGURED':'NOT CONFIGURED'}},slot,blockHeight:block,updatedAt:new Date().toISOString()})}
 if(!u)return json(res,401,{error:'AUTH_REQUIRED'});
 if(url.pathname==='/api/ai/decisions')return json(res,200,{decisions:store.decisions(u.id).map(candidateView)});
 if(url.pathname==='/api/settings'&&req.method==='GET')return json(res,200,{settings:u.settings,version:u.updatedAt||1,killSwitchActive:u.killSwitch,capabilities:{liveAutomation:u.liveEntitled}});
 if(url.pathname==='/api/settings'&&req.method==='PUT'){const b=await body(req);return json(res,200,{settings:store.setSettings(u.id,b.settings||{}),version:Date.now()})}
 if(url.pathname==='/api/settings/defaults'&&req.method==='POST')return json(res,200,{settings:store.setSettings(u.id,defaults())});
 if(url.pathname==='/api/settings/kill-switch'&&req.method==='POST'){u.killSwitch=true;store.save();return json(res,200,{active:true})}
 if(url.pathname==='/api/owner/status')return json(res,200,{isOwner:Boolean(u.isOwner),entitlementSource:u.isOwner?'owner':'none'});
 if(url.pathname==='/api/owner/claim'&&req.method==='POST'){if(!OWNER_ACCESS_KEY)return json(res,503,{error:'OWNER_ACCESS_NOT_CONFIGURED'});const b=await body(req);const supplied=String(b.accessKey||'');const a=Buffer.from(OWNER_ACCESS_KEY),c=Buffer.from(supplied);if(a.length!==c.length||!crypto.timingSafeEqual(a,c))return json(res,403,{error:'INVALID_OWNER_ACCESS_KEY'});store.grantOwner(u.id,'owner_access_key');return json(res,200,{isOwner:true,liveEntitled:true,entitlementSource:'owner'});}
 if(url.pathname==='/api/billing/status')return json(res,200,billingStatus(u));
 if(url.pathname==='/api/billing/checkout'&&req.method==='POST'){if(!billing.configured)return json(res,503,{error:'BILLING_NOT_CONFIGURED',message:'Configure STRIPE_SECRET_KEY, STRIPE_PRICE_ID and STRIPE_WEBHOOK_SECRET.'});try{const session=await billing.createCheckout(u,origin(req));return json(res,200,{url:session.url,id:session.id})}catch(e){return json(res,e.status||502,{error:e.code||'STRIPE_ERROR',message:e.message})}}
 if(url.pathname==='/api/billing/portal'&&req.method==='POST'){if(!billing.configured)return json(res,503,{error:'BILLING_NOT_CONFIGURED'});try{const session=await billing.createPortal(u,origin(req));return json(res,200,{url:session.url})}catch(e){return json(res,e.status||502,{error:e.code||'STRIPE_ERROR',message:e.message})}}
 if(url.pathname==='/api/discovery/status')return json(res,200,{...discovery,metrics:store.state.metrics,tokens:store.tokens().length,users:Object.keys(store.state.users).length});
 if(url.pathname==='/api/chart/config')return json(res,200,{chainId:'solana',tokenAddress:store.decisions(u.id)[0]?.mint||''});
 if(url.pathname==='/api/chart/history'){const mint=url.searchParams.get('tokenAddress'),t=store.state.tokens[mint];const pts=t?.priceSol?[{t:t.updatedAt,price:t.priceSol,source:t.source}]:[];return json(res,200,{points:pts,status:{stale:!pts.length,source:t?.source||null,error:t?.scanError||null},tokenAddress:mint})}
 if(url.pathname==='/api/chart/stream'){const mint=url.searchParams.get('tokenAddress');res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive'});res.write(`event: snapshot\ndata: ${JSON.stringify({points:[],status:{stale:true,source:'Solana'}})}\n\n`);if(!streams.has(mint))streams.set(mint,new Set());streams.get(mint).add(res);req.on('close',()=>streams.get(mint)?.delete(res));return}
 if(url.pathname==='/api/live/execute'){if(!hasLiveEntitlement(u))return json(res,402,{error:'LIVE_ENTITLEMENT_REQUIRED',message:'An active MEMEFLOW Pro subscription or verified owner entitlement is required.'});return json(res,423,{error:'LIVE_EXECUTION_NOT_READY',message:u.isOwner?'Owner LIVE entitlement is active, but verified wallet and production execution engine are still required.':'Pro is active, but verified wallet and production execution engine are still required.'})}
 const p=url.pathname==='/'?'index.html':url.pathname.slice(1);const f=path.resolve(root,p);if(!f.startsWith(root)||!fs.existsSync(f)||fs.statSync(f).isDirectory())return json(res,404,{error:'NOT_FOUND'});
 const ext=path.extname(f).toLowerCase();
 const MIME={'':' text/plain','html':'text/html; charset=utf-8','htm':'text/html; charset=utf-8','js':'text/javascript; charset=utf-8','mjs':'text/javascript; charset=utf-8','css':'text/css; charset=utf-8','json':'application/json; charset=utf-8','svg':'image/svg+xml','ico':'image/x-icon','png':'image/png','jpg':'image/jpeg','jpeg':'image/jpeg','webp':'image/webp','woff':'font/woff','woff2':'font/woff2','ttf':'font/ttf'};
 const mime=MIME[ext.slice(1)]||'application/octet-stream';
 const isText=mime.startsWith('text/')||mime.includes('javascript')||mime.includes('json')||mime.includes('svg');
 const isHTML=ext==='.html'||ext==='.htm';
 // HTML: no-store (always fresh). Static assets (JS/CSS): 1-hour cache with revalidation.
 const cacheHeader=isHTML?'no-store, no-cache, must-revalidate':'public, max-age=3600, stale-while-revalidate=86400';
 res.setHeader('content-type',mime);
 res.setHeader('cache-control',cacheHeader);
 if(isHTML){res.setHeader('pragma','no-cache');res.setHeader('expires','0')}
 // Gzip/Brotli for text assets when the client supports it
 const ae=req.headers['accept-encoding']||'';
 const stat=fs.statSync(f);
 if(isText&&stat.size>512){
   if(ae.includes('br')){
     res.setHeader('content-encoding','br');res.setHeader('vary','Accept-Encoding');
     const br=zlib.createBrotliCompress({params:{[zlib.constants.BROTLI_PARAM_QUALITY]:4}});
     fs.createReadStream(f).pipe(br).pipe(res);
   } else if(ae.includes('gzip')){
     res.setHeader('content-encoding','gzip');res.setHeader('vary','Accept-Encoding');
     const gz=zlib.createGzip({level:6});
     fs.createReadStream(f).pipe(gz).pipe(res);
   } else {
     fs.createReadStream(f).pipe(res);
   }
 } else {
   fs.createReadStream(f).pipe(res);
 }
}
const server=http.createServer((req,res)=>handler(req,res).catch(e=>json(res,500,{error:'SERVER_ERROR',message:e.message})));server.listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log(`MEMEFLOW listening on ${process.env.PORT||3000}`));
