import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const cwd=process.cwd();
const appDir=fs.existsSync(path.join(cwd,'memeflow-app'))?path.join(cwd,'memeflow-app'):cwd;
const {evaluate,tokenAgeMinutes}=await import(pathToFileURL(path.join(appDir,'src','evaluate.mjs')).href);
const now=Date.now();
const token={mint:'TEST',discoveredAt:now-10*60000,ageMinutes:2,priceSol:1,peakPriceSol:1,lastPriceAt:now,lastPriceChangeAt:now,lastMarketActivityAt:now,waitingSince:now,holderCount:50,top10Pct:10,developerPct:1,buyPressure:2,holderFresh:true,dataQuality:1};
const settings={maxTokenAgeMinutes:5,minTokenAgeMinutes:null,minHolders:null,maxHolders:null,minTop10Pct:null,maxTop10Pct:null,minDeveloperPct:null,maxDeveloperPct:null,minBuyPressure:null,minScore:0,minConfidence:0,requireFreshHolderSnapshot:false,launchPlatforms:[],includeKeywords:'',excludeKeywords:'',developerBlacklistWallets:[]};
assert(tokenAgeMinutes(token,now)>9.9);
const expired=evaluate(token,settings);assert.equal(expired.state,'EXPIRED');assert.match(expired.primaryReason,/Token age 10\./);
const stale=evaluate({...token,discoveredAt:now-60000,lastPriceAt:now-31000},{...settings,maxTokenAgeMinutes:180});assert.equal(stale.state,'EXPIRED');assert.match(stale.primaryReason,/Price feed is stale/);
const server=fs.readFileSync(path.join(appDir,'app-server.mjs'),'utf8');
assert(server.includes("import {evaluate,tokenAgeMinutes} from './src/evaluate.mjs';"));
assert(server.includes('ageMinutes:tokenAgeMinutes(t)'));
assert(server.includes('quoteAgeMs:t.lastPriceAt?Math.max(0,Date.now()-t.lastPriceAt):null'));
assert(server.includes('await evaluateAll(store.state.tokens[mint]);publish(mint)'));
assert(server.includes('scanError:e.message});await evaluateAll(store.state.tokens[mint])'));
console.log('PASS: displayed age and AI reason use the same live age');
console.log('PASS: stale price quote becomes EXPIRED');
console.log('PASS: quoteAgeMs uses last successful quote time');
console.log('PASS: live polling and RPC errors trigger re-evaluation');
