import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {defaultSettings,normalizeSettings,validateSettings} from './settings.mjs';
import {evaluate} from './evaluate.mjs';
const NOW=Date.now();
const token=(p={})=>({
 mint:'V15Risk111111111111111111111111111pump',name:'V15 Risk',symbol:'V15',launchPlatform:'pump',protocol:'pump',source:'Pump create',
 discoveredAt:NOW-5*60_000,pumpCreatedAt:NOW-5*60_000,pumpCreatedAtPending:false,
 holderCount:120,holderFresh:true,top10Pct:10,developerPct:2,buyPressure:3,priceSol:1,peakPriceSol:1,dataQuality:1,
 liquidityUsd:1_000_000,marketCapUsd:1_000_000,bondingCurvePct:10,bondingCurveProgressPct:10,volume24hUsd:1_000_000,
 buys24h:100,sells24h:10,buyTransactions:100,sellTransactions:10,totalTransactions:110,totalFeesSol:100,bundlePct:0,sniperPct:0,
 twitter:'https://x.com/v15',website:'https://example.invalid',metadataResolved:true,metadataReady:true,imageUrl:'https://example.invalid/logo.png',
 devMigrated:true,suspectedRiskyWalletsPct:1,insidersPct:1,developerRugHistoryPct:0,developerExitPct:0,...p
});
const cfg=(p={})=>normalizeSettings({...defaultSettings(),minScore:0,minConfidence:0,minHolders:null,maxHolders:null,minLiquidityUsd:null,minMarketCapUsd:null,maxMarketCapUsd:null,minBondingCurvePct:null,maxBondingCurvePct:null,minBondingCurveProgressPct:null,maxBondingCurveProgressPct:null,minVolume24hUsd:null,maxVolume24hUsd:null,minBuyTransactions:null,maxBuyTransactions:null,minSellTransactions:null,maxSellTransactions:null,minTotalTransactions:null,maxTotalTransactions:null,minBuys24h:null,maxBuys24h:null,minSells24h:null,maxSells24h:null,minBundlePct:null,maxBundlePct:null,minSniperPct:null,maxSniperPct:null,minTokenAgeMinutes:null,maxTokenAgeMinutes:null,requireFreshHolderSnapshot:false,requireAnySocial:false,requireTwitter:false,requireWebsite:false,requireTelegram:false,requireWebsiteOrX:false,maxTop10Pct:25,maxDeveloperPct:20,maxSuspectedRiskyWalletsPct:null,maxInsidersPct:null,requireDevMigrated:false,maxDeveloperRugHistoryPct:null,maxDeveloperExitPct:null,requireTokenLogo:false,...p});

test('V1.5 settings defaults are disabled and valid values persist',()=>{const d=defaultSettings();assert.equal(d.maxSuspectedRiskyWalletsPct,null);assert.equal(d.maxInsidersPct,null);assert.equal(d.requireDevMigrated,false);assert.equal(d.maxDeveloperRugHistoryPct,null);assert.equal(d.maxDeveloperExitPct,null);assert.equal(d.requireTokenLogo,false);const v=validateSettings({...d,maxSuspectedRiskyWalletsPct:12.5,maxInsidersPct:8,requireDevMigrated:true,maxDeveloperRugHistoryPct:15,maxDeveloperExitPct:20,requireTokenLogo:true});assert.equal(v.ok,true,v.errors?.join('; '));assert.equal(v.settings.maxSuspectedRiskyWalletsPct,12.5);assert.equal(v.settings.requireTokenLogo,true)});
test('invalid V1.5 percentage is rejected',()=>{const v=validateSettings({...defaultSettings(),maxInsidersPct:101});assert.equal(v.ok,false);assert.match(v.errors.join(' '),/maxInsidersPct/)});
test('disabled unknown new metrics do not create V1.5 gates',()=>{const d=evaluate(token({suspectedRiskyWalletsPct:null,insidersPct:null,developerRugHistoryPct:null,developerExitPct:null,devMigrated:null}),cfg());const n=d.settingsEvaluation.gates.map(g=>g.name);assert.equal(n.includes('Suspected risky wallets'),false);assert.equal(n.includes('Insiders'),false);assert.equal(n.includes('Developer migrated'),false)});
test('unknown enabled risky-wallet evidence waits',()=>{const d=evaluate(token({suspectedRiskyWalletsPct:null}),cfg({maxSuspectedRiskyWalletsPct:10}));assert.equal(d.state,'WAITING');assert.equal(d.settingsEvaluation.gates.find(g=>g.name==='Suspected risky wallets')?.status,'WAITING')});
test('known risky-wallet violation blocks',()=>{const d=evaluate(token({suspectedRiskyWalletsPct:12}),cfg({maxSuspectedRiskyWalletsPct:10}));assert.equal(d.state,'BLOCKED')});
test('insiders unknown waits and known violation blocks',()=>{assert.equal(evaluate(token({insidersPct:null}),cfg({maxInsidersPct:10})).state,'WAITING');assert.equal(evaluate(token({insidersPct:11}),cfg({maxInsidersPct:10})).state,'BLOCKED')});
test('developer rug history and exit are explicit evidence gates',()=>{assert.equal(evaluate(token({developerRugHistoryPct:21}),cfg({maxDeveloperRugHistoryPct:20})).state,'BLOCKED');assert.equal(evaluate(token({developerExitPct:null}),cfg({maxDeveloperExitPct:20})).state,'WAITING')});
test('dev migrated unknown waits, false blocks, true passes',()=>{assert.equal(evaluate(token({devMigrated:null}),cfg({requireDevMigrated:true})).state,'WAITING');assert.equal(evaluate(token({devMigrated:false}),cfg({requireDevMigrated:true})).state,'BLOCKED');const d=evaluate(token({devMigrated:true}),cfg({requireDevMigrated:true}));assert.notEqual(d.state,'BLOCKED');assert.equal(d.settingsEvaluation.gates.find(g=>g.name==='Developer migrated')?.status,'PASS')});
test('token logo waits for metadata then missing logo blocks',()=>{assert.equal(evaluate(token({imageUrl:null,metadataResolved:false,metadataReady:false,metadataFetched:false,metadataFetchedAt:null}),cfg({requireTokenLogo:true})).state,'WAITING');assert.equal(evaluate(token({imageUrl:null,metadataResolved:true,metadataReady:true}),cfg({requireTokenLogo:true})).state,'BLOCKED');assert.notEqual(evaluate(token({imageUrl:'https://example.invalid/logo.png',metadataResolved:true}),cfg({requireTokenLogo:true})).state,'BLOCKED')});
test('existing bundle/sniper unknown-enabled behavior stays WAITING',()=>{assert.equal(evaluate(token({bundlePct:null,bundledPct:null,bundlePercentage:null}),cfg({maxBundlePct:10})).state,'WAITING');assert.equal(evaluate(token({sniperPct:null,snipersPct:null,sniperPercentage:null}),cfg({maxSniperPct:10})).state,'WAITING')});
test('Top-10 and Developer remain authoritative',()=>{assert.equal(evaluate(token({top10Pct:30}),cfg({maxTop10Pct:25})).state,'BLOCKED');assert.equal(evaluate(token({developerPct:21}),cfg({maxDeveloperPct:20})).state,'BLOCKED')});
test('V1.5 evaluator block contains no DEX price inputs',()=>{const src=fs.readFileSync(new URL('./evaluate.mjs',import.meta.url),'utf8');const i=src.lastIndexOf('// MEMEFLOW_ANTI_RUG_V1_5_EXACT');assert.ok(i>=0);const b=src.slice(i);assert.doesNotMatch(b,/dexPrice|dexPriceUsd|dexPriceSol|poolPrice|quotePrice/i);assert.match(b,/suspectedRiskyWalletsPct/);assert.match(b,/insidersPct/);assert.match(b,/developerRugHistoryPct/);assert.match(b,/developerExitPct/)});
