// MEMEFLOW V12.17 EVENT HOLDER LEDGER
import fs from 'node:fs'; import path from 'node:path';
const VERSION='V12.17', STATE=process.env.EVENT_HOLDER_LEDGER_STATE_PATH||path.join(process.cwd(),'data','event-holder-ledger-v12-17.json');
const raw=e=>{try{return BigInt(String(e?.uiTokenAmount?.amount??e?.amount??0))}catch{return 0n}};
const mint=e=>e?.mint?.toString?.()||e?.mint||null, owner=e=>e?.owner?.toString?.()||e?.owner||null;
const pump=m=>typeof m==='string'&&m.toLowerCase().endsWith('pump');
const pct=(n,d)=>d>0n?Number((n*100000n)/d)/1000:null;
function signer(tx){const ks=tx?.transaction?.message?.accountKeys||[];for(const k of ks)if(k&&typeof k==='object'&&k.signer)return k.pubkey?.toString?.()||String(k.pubkey||'');return typeof ks[0]==='string'?ks[0]:ks[0]?.pubkey?.toString?.()||null}
export class EventHolderLedger{
 constructor(){this.byMint=new Map();this.metrics={version:VERSION,transactionsSeen:0,pumpTransactionsSeen:0,mintsSeen:0,holderSnapshots:0,writes:0,writeErrors:0,loadedMints:0,lastTxAt:null,lastMint:null,lastError:null};this.t=null;this.load()}
 row(m){let r=this.byMint.get(m);if(!r){r={mint:m,creator:null,balances:new Map(),firstSeenAt:Date.now(),lastSeenAt:null,txCount:0};this.byMint.set(m,r);this.metrics.mintsSeen++}return r}
 ingestTransaction(tx){this.metrics.transactionsSeen++;this.metrics.lastTxAt=Date.now();const meta=tx?.meta||tx?.transaction?.meta||{},pre=meta.preTokenBalances||[],post=meta.postTokenBalances||[],ms=new Set([...pre,...post].map(mint).filter(pump));if(!ms.size)return[];this.metrics.pumpTransactionsSeen++;const first=signer(tx),out=[];for(const m of ms){const r=this.row(m);r.txCount++;r.lastSeenAt=Date.now();if(!r.creator&&r.txCount===1&&first)r.creator=first;const p0=pre.filter(e=>mint(e)===m),p1=post.filter(e=>mint(e)===m),seen=new Set();for(const e of p1){const o=owner(e);if(!o)continue;seen.add(o);const a=raw(e);if(a>0n)r.balances.set(o,a);else r.balances.delete(o)}for(const e of p0){const o=owner(e);if(o&&!seen.has(o))r.balances.delete(o)}const s=this.snapshot(m);if(s){out.push(s);this.metrics.holderSnapshots++;this.metrics.lastMint=m}}this.schedule();return out}
 snapshot(m){const r=this.byMint.get(m);if(!r)return null;const v=[...r.balances].filter(([,a])=>a>0n).sort((a,b)=>a[1]===b[1]?0:a[1]>b[1]?-1:1),total=v.reduce((x,[,a])=>x+a,0n),top=v.slice(0,10).reduce((x,[,a])=>x+a,0n),dev=r.creator?(r.balances.get(r.creator)||0n):0n;return{mint:m,holderFresh:true,holderSource:'event-ledger',holderCount:v.length,top10Pct:pct(top,total),developerPct:r.creator?pct(dev,total):null,developerSharePct:r.creator?pct(dev,total):null,holderScannedAt:r.lastSeenAt||Date.now(),eventLedgerVersion:VERSION,eventLedgerTxCount:r.txCount,eventLedgerCreator:r.creator,eventLedgerTrackedSupplyRaw:total.toString()}}
 applyToStore(store,m){const s=this.snapshot(m);if(!s||!store?.setToken)return null;try{return store.setToken(m,s)||s}catch(e){this.metrics.lastError=String(e?.message||e);return null}}
 inspect(m){return this.snapshot(m)} diagnostics(){return{...this.metrics,trackedMints:this.byMint.size}}
 schedule(){if(this.t)return;this.t=setTimeout(()=>{this.t=null;this.save()},1000);this.t.unref?.()}
 save(){try{fs.mkdirSync(path.dirname(STATE),{recursive:true});const o={version:VERSION,savedAt:Date.now(),mints:{}};for(const[m,r]of this.byMint)o.mints[m]={creator:r.creator,firstSeenAt:r.firstSeenAt,lastSeenAt:r.lastSeenAt,txCount:r.txCount,balances:Object.fromEntries([...r.balances].map(([k,v])=>[k,v.toString()]))};fs.writeFileSync(STATE+'.tmp',JSON.stringify(o));fs.renameSync(STATE+'.tmp',STATE);this.metrics.writes++}catch(e){this.metrics.writeErrors++;this.metrics.lastError=String(e?.message||e)}}
 load(){try{if(!fs.existsSync(STATE))return;const o=JSON.parse(fs.readFileSync(STATE,'utf8'));for(const[m,s]of Object.entries(o.mints||{})){const r={mint:m,creator:s.creator||null,firstSeenAt:s.firstSeenAt||Date.now(),lastSeenAt:s.lastSeenAt||null,txCount:s.txCount||0,balances:new Map()};for(const[k,v]of Object.entries(s.balances||{})){try{const a=BigInt(v);if(a>0n)r.balances.set(k,a)}catch{}}this.byMint.set(m,r);this.metrics.loadedMints++}}catch(e){this.metrics.lastError='load:'+String(e?.message||e)}}
}
export const eventHolderLedger=new EventHolderLedger();
