import test from 'node:test';import assert from 'node:assert/strict';import {defaultSettings,normalizeSettings,validateSettings} from './settings.mjs';import {evaluate} from './evaluate.mjs';
const baseToken=(patch={})=>({holderCount:50,holderFresh:true,priceSol:1,dataQuality:1,buyPressure:2,top10Pct:20,developerPct:10,source:'Pump create',discoveredAt:Date.now(),...patch});

test('defaults retain AI thresholds and new ranges',()=>{const s=defaultSettings();assert.equal(s.minScore,72);assert.equal(s.minHolders,30);assert.equal(s.maxTop10Pct,25)});
test('empty ranges normalize to null and zero remains valid',()=>{const s=normalizeSettings({minHolders:'',maxHolders:0});assert.equal(s.minHolders,null);assert.equal(s.maxHolders,0)});
test('invalid min/max rejected',()=>assert.equal(validateSettings({minHolders:50,maxHolders:10}).ok,false));
test('holder range blocks below minimum',()=>{const d=evaluate({holderCount:17,holderFresh:true,priceSol:1,dataQuality:1,buyPressure:2,top10Pct:20,developerPct:10,source:'Pump create',discoveredAt:Date.now()},{...defaultSettings(),minHolders:30,maxHolders:100});assert.equal(d.state,'BLOCKED')});
test('missing enabled bundle data waits',()=>{const d=evaluate({holderCount:50,holderFresh:true,priceSol:1,dataQuality:1,buyPressure:2,source:'Pump create',discoveredAt:Date.now()},{...defaultSettings(),minBundlePct:0,maxBundlePct:10});assert.equal(d.state,'WAITING')});
test('top10 range and AI thresholds work together',()=>{const d=evaluate({holderCount:50,holderFresh:true,priceSol:1,dataQuality:1,buyPressure:2,top10Pct:20,developerPct:10,source:'Pump create',discoveredAt:Date.now()},{...defaultSettings(),minTop10Pct:0,maxTop10Pct:25});assert.equal(d.state,'BUY READY')});

test('maximum holders blocks above configured limit',()=>{const s=normalizeSettings({...defaultSettings(),minHolders:null,maxHolders:100,requireFreshHolderSnapshot:false,minBuyPressure:null});const d=evaluate(baseToken({holderCount:101}),s);assert.equal(d.state,'BLOCKED');assert.match(d.reasons.join(' '),/above maximum 100/)});
test('holder range passes inside inclusive boundaries',()=>{const s=normalizeSettings({...defaultSettings(),minHolders:30,maxHolders:100,requireFreshHolderSnapshot:false,minBuyPressure:null,minScore:0,minConfidence:0});const d=evaluate(baseToken({holderCount:30}),s);assert.notEqual(d.state,'BLOCKED')});
test('required social link blocks when missing',()=>{const s=normalizeSettings({...defaultSettings(),minHolders:null,maxTop10Pct:null,maxDeveloperPct:null,minTokenAgeMinutes:null,maxTokenAgeMinutes:null,requireFreshHolderSnapshot:false,minBuyPressure:null,requireTwitter:true});const d=evaluate(baseToken({twitter:null}),s);assert.equal(d.state,'BLOCKED');assert.match(d.reasons.join(' '),/Twitter\/X required/)});
test('launch platform filter accepts Pump create source',()=>{const s=normalizeSettings({...defaultSettings(),launchPlatforms:['pump'],minHolders:null,maxTop10Pct:null,maxDeveloperPct:null,minTokenAgeMinutes:null,maxTokenAgeMinutes:null,requireFreshHolderSnapshot:false,minBuyPressure:null,minScore:0,minConfidence:0});const d=evaluate(baseToken({source:'Pump create'}),s);assert.notEqual(d.state,'BLOCKED')});
test('developer blacklist blocks exact creator wallet',()=>{const s=normalizeSettings({...defaultSettings(),developerBlacklistWallets:['Creator111'],minHolders:null,maxTop10Pct:null,maxDeveloperPct:null,minTokenAgeMinutes:null,maxTokenAgeMinutes:null,requireFreshHolderSnapshot:false,minBuyPressure:null});const d=evaluate(baseToken({creator:'Creator111'}),s);assert.equal(d.state,'BLOCKED');assert.match(d.reasons.join(' '),/Developer wallet/)});
test('missing enabled metric produces WAITING instead of false zero',()=>{const s=normalizeSettings({...defaultSettings(),minVolume24hUsd:1000,minHolders:null,maxTop10Pct:null,maxDeveloperPct:null,minTokenAgeMinutes:null,maxTokenAgeMinutes:null,requireFreshHolderSnapshot:false,minBuyPressure:null});const d=evaluate(baseToken({volume24hUsd:null}),s);assert.equal(d.state,'WAITING');assert.match(d.reasons.join(' '),/24h volume data pending/)});
