const ALPH='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
export function b58decode(s){let n=0n;for(const c of s){const i=ALPH.indexOf(c);if(i<0)throw Error('invalid base58');n=n*58n+BigInt(i)}let h=n.toString(16);if(h.length%2)h='0'+h;let b=Buffer.from(h,'hex');let z=0;while(s[z]==='1')z++;return Buffer.concat([Buffer.alloc(z),b])}
export function validPubkey(s){try{return b58decode(s).length===32}catch{return false}}
export class RpcPool{
 constructor(urls,commitment='confirmed'){this.urls=urls.filter(Boolean);this.commitment=commitment;this.i=0;this.last={ok:false,latency:null,url:null,error:'not checked'}}
 async call(method,params=[]){if(!this.urls.length)throw Error('SOLANA_RPC_URLS is not configured');let last;for(let k=0;k<this.urls.length;k++){const url=this.urls[(this.i+k)%this.urls.length],c=new AbortController(),t=setTimeout(()=>c.abort(),9000),start=Date.now();try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params}),signal:c.signal});const j=await r.json();if(!r.ok||j.error)throw Error(j.error?.message||`RPC ${r.status}`);this.i=(this.i+k)%this.urls.length;this.last={ok:true,latency:Date.now()-start,url,error:null};return j.result}catch(e){last=e;this.last={ok:false,latency:Date.now()-start,url,error:e.message}}finally{clearTimeout(t)}}throw last||Error('RPC failed')}
}
export function u64(buf,o){return Number(buf.readBigUInt64LE(o))}
export function decodeCurve(base64,decimals=6){const b=Buffer.from(base64,'base64');if(b.length<49)throw Error('Bonding curve account too short');let o=8;const virtualToken=u64(b,o);o+=8;const virtualSol=u64(b,o);o+=8;const realToken=u64(b,o);o+=8;const realSol=u64(b,o);o+=8;const supply=u64(b,o);o+=8;const complete=Boolean(b[o]);const priceSol=virtualToken>0?(virtualSol/1e9)/(virtualToken/10**decimals):null;return {virtualToken,virtualSol,realToken,realSol,supply,complete,priceSol,liquiditySol:realSol/1e9}}
export function decodeCreateData(data){try{const b=b58decode(data),disc=[...b.subarray(0,8)],create='24,30,200,40,5,28,7,119',create2='214,144,76,236,95,139,49,180';if(disc.join(',')!==create&&disc.join(',')!==create2)return null;let o=8;const str=()=>{const n=b.readUInt32LE(o);o+=4;const s=b.subarray(o,o+n).toString('utf8');o+=n;return s};return {kind:disc.join(',')===create?'create':'create_v2',name:str(),symbol:str(),uri:str()}}catch{return null}}
